Sprint 1/step 2
vanichh/react-burger pull request #3
Opened 2021-12-08 12:43 UTC by vanichh

Вместо  propTypes использовал типизацию через TS, в остальном вроде все ок, проверил по чеклисту

2021-12-08 20:17 UTC, grishbar requested changes
Проделана отличная работа, корректно воспользовался порталом и верно реализовал весь функционал, исправь пожалуйста следующие моменты, для принятия работы:

- [ ] Переименовать неудачно названные переменные
- [ ] Вынести константы из компонентов и назвать их в SNAKE_CASE

Также обрати внимание на комментарии можно лучше, они помогут тебе сделать работу более качественной.

2021-12-08 20:17 UTC, grishbar commented on src/App.tsx
> +import DATA from './utils/data';
`надо исправить`
data слишком абстрактное название, требуется называть переменные так, как будто их будут читать совершенно незнакомые люди. Так, чтобы любой человек который будет видеть твою переменную смог примерно понять, что в ней находится. Побольше насчет корректного названия переменных можно почитать [здесь](https://thecode.media/variables/)

2021-12-08 20:17 UTC, grishbar commented on src/App.tsx
> +                <BurgerIngredients data={DATA} />
`надо исправить`
соответственно тут пропсы data у компонентов тоже надо переименовать

2021-12-08 20:17 UTC, grishbar commented on src/components/app/app.tsx
> +        const urlString = 'https://norma.nomoreparties.space/api/ingredients';
`надо исправить`
такие константые переменные должны находиться снаружи компоненты и быть называны в SNAKE_CASE, так сразу становится понятно, что это переменная константна и меняться не должна, также тут можно поработать и над названием переменной
```
const INGREDIENTS_URL = 'https://norma.nomoreparties.space/api/ingredients';
```

2021-12-08 20:17 UTC, grishbar commented on src/components/app/app.tsx
> +    }, []);
`отлично`
сам запрос сделал абсолютно корректно обработал ошибки и статус ответа и вызываешь только один раз

2021-12-08 20:17 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +    const [isModal, setisModal] = useState(false);
`можно лучше`
скорее isModalOpen

2021-12-08 20:17 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +            <Modal title='no' IsOpen={setisModal}>
`надо исправить`
пропсы компонентов должны быть с маленькой буквы и кажется эта переменная должна называться setIsModalOpen

2021-12-08 20:17 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +// import PropTypes from 'prop-types';
`надо исправить`
комментарии которые не документируют дальнейший код (не говорят, что будет происходит в последующих строчках под ними) должны быть удалены

2021-12-08 20:17 UTC, grishbar commented on src/components/modal-overlay/modal-overlay.tsx
> +    };
`надо исправить`
функции которые обрабатывают определенные события должны начинаться со слова handle и closewindows какое то плохое название намного лучше будет -  handleCloseModal

2021-12-09 08:48 UTC, vanichh commented on src/App.tsx
> +import DATA from './utils/data';
Этот компонент я должен бы удалить, просто перейдя на другой пк забыл его удалить.

2021-12-10 02:41 UTC, grishbar approved these changes
Отлично работу засчитываю, удачи в дальнейшем обучении

2021-12-10 02:41 UTC, grishbar commented on src/components/app/app.tsx
> +    const [dataIngredients, setDataIngredients] = useState([]);
`можно лучше`
слово data излишнее как по мне, но можно так оставить тоже отличное название

2021-12-10 02:41 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +const ARR_TYPE_INGREDIENT: ingredientType[] = ['bun', 'sauce', 'main'];
`отлично`
круто что вынес эту константу из компонента 👍

2021-12-15 15:21 UTC, merged